title: Graveflli
email: 7419977@gmail.com
SEOTitle: Graveflli's blog
description: >- # this means to ignore newlines until "baseurl:"
  "他们说的话,我连标点符号都不信."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Graveflli

# Build settings
theme: minima
# theme: jekyll-midnight-theme
# remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
#  - jekyll-remote-theme

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Friends
friends: [
    {
        title: "soloben",
        href: "https://soloisben.github.io"
    }
]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
